python: /home/public/miniconda3/envs/agent/bin/python
document:
  category_name: Design
  tool_name: proteinmpnn
  tool_description: This tool designs protein sequences with specific structures.
    Specifically, proteinmpnn is to alter or design amino acid sequences
    to obtain novel proteins with desired properties. 
  required_parameters:
  - name: protein_structure
    type: PATH
    detailed_type: STRUCTURE_PATH
    description: The Path to the protein backbone structure. Usually a .pdb file. Full atom structure could also
      be used, but only the backbone atoms will be used for design. The input structure
      should be a single chain or a homooligomeric structure. The tool will not work
      with multi-chain structures.
  optional_parameters:
  - name: chains
    type: TEXT
    detailed_type: CHAIN_ID
    description: Indicates the specific chain(s) within the PDB structure to be used
      for sequence prediction. Multiple chains can be specified if needed.
    default: A
  - name: homooligomer
    type: BOOLEAN
    detailed_type: HOMOOLIGOMER
    description: Indicates if the design is for a homooligomer.
    default: False
  - name: fix_pos
    type: TEXT
    detailed_type: FIX_POS
    description: Specify which positions to keep fixed in the sequence. You can also
      specify chain specific constraints or to fix entire chain(s).
    default: ~
  - name: inverse
    type: BOOLEAN
    detailed_type: INVERSE_FIX_POS
    description: Inverse the fix_pos selection to define positions to 'free' [or design]
      instead of 'fix'.
    default: False
  - name: rm_aa
    type: TEXT
    detailed_type: EXCLUDED_AA
    description: Specify amino acid(s) to exclude from the design.
    default: ~
  - name: num_seqs
    type: INTEGER
    detailed_type: DESIGN_NUM
    description: Number of sequences to generate.
    default: 32
  - name: sampling_temp
    type: FLOAT
    detailed_type: TEMPERATURE
    description: Sampling temperature for amino acids. T=0.0 means taking argmax,
      T>>1.0 means sample randomly.
    default: 0.1
  - name: model_name
    type: SELECTION
    detailed_type: MPNN_MODEL
    description: The name of the model to use for sequence design. The model is
      a trained neural network that predicts the most likely amino acid sequence
      based on the input protein structure.
    choices:
    - v_48_002
    - v_48_010
    - v_48_020
    - v_48_030
    default: v_48_002
  return_values:
  - name: best_sequence
    type: SEQUENCE
    detailed_type: AA_SEQUENCE
    description: The best sequence generated by the model.
  - name: full_result
    type: PATH
    detailed_type: MPNN_CSV_PATH
    description: The full result of the model. This is a csv file that includes all samples.
  - name: full_fasta
    type: PATH
    detailed_type: FASTA_PATH
    description: The full result of the model in FASTA format. This is a text file that includes all.
  return_scores:
  - name: best_score
    description: The score of the best sequence generated by the model.
