example_output:
  sequence_path: cluster_result.fasta
bin: bin/mmseqs
script: mmseqs_cluster.sh
document:
  category_name: Sequence
  tool_name: mmseqs_cluster
  tool_description: MMseqs2 is a fast and sensitive
    tool for clustering large protein sequence datasets. It groups similar sequences
    into clusters, which can be useful for reducing redundancy and identifying representative
    sequences. In this tool, we only keep the representative sequences as clustering
    result
  required_parameters:
  - name: sequence_path
    type: PATH
    detailed_type: FASTA_PATH
    description: A set of protein sequences to be clustered using MMseqs2.
  optional_parameters:
  - name: identity
    type: FLOAT
    detailed_type: SEQUENCE_IDENTITY
    description: The sequence identity threshold for clustering. Sequences with identity
      above this threshold will be grouped into the same cluster.
    default: 0.5
  return_values:
  - name: sequence_path
    type: PATH
    detailed_type: FASTA_PATH
    description: The representative sequences in each clusters, where each cluster
      represents a group of similar sequences.
  return_scores:
  - name: results_num
    description: Number of clusters generated by mmseqs_cluster.
  - name: duration
    description: Total time spent clustering (unit of measurement in seconds).