example_output:
  save_path: pinal_designs.csv

python: /home/public/miniconda3/envs/agent/bin/python
document:
  category_name: Design
  tool_name: pinal
  tool_description: A tool for text-guided de novo protein design, enabling the generation
    of novel protein sequences based on textual descriptions. We only return a success
    status for you. The actual protein designs are provided in task manager.
  required_parameters:
  - name: input_text
    type: TEXT
    detailed_type: TEXT
    description: A textual input that provides the design guidance for the protein
      sequence. This text describes the desired function or characteristics of the
      target protein. The more detailed the input text, the more specific the generated
      protein designs will be.
  optional_parameters:
  - name: design_num
    type: INTEGER
    detailed_type: DESIGN_NUM
    description: The number of protein designs to generate based on the input guidance.
      If not specified, the default value is 5.
    default: 5
  return_values:
  - name: full_result
    type: PATH
    detailed_type: PINAL_CSV_PATH
    description: The save path of the generated table containing the protein designs.
  - name: full_fasta
    type: PATH
    detailed_type: FASTA_PATH
    description: The save path of the generated FASTA file containing the protein designs.
  - name: best_sequence
    type: TEXT
    detailed_type: AA_SEQUENCE
    description: The best protein sequence generated by the model based on the input text.
  return_scores:
  - name: max_logp
    description: Log(p) per token can be viewed as a confidence metric, empirically, Log(p) per token values above -1 indicate high-confidence designs.
  - name: max_protrek_score
    description: Protrek Scores exceeding 15 suggest strong sequence-text alignment. Proteins scoring below 10 on Protrek can be considered irrelevant.
