python: /home/public/miniconda3/envs/agent/bin/python

document:
  category_name: Knowledge
  tool_name: biorxiv
  tool_description: Help users find literatures/articles/papers on the biorxiv preprint
    server. These keywords could be extracted by llm in the given context.
  required_parameters:
  - name: keywords
    type: TEXT
    detailed_type: TEXT
    description: >
      A short and precise term to search within all articles on biorxiv preprint server.
      The term must:
      - Be 1-3 words maximum (no long phrases)
      - Use standard MeSH/Emtree terminology when applicable
      - Represent core concepts (avoid peripheral terms)
      - Include semantic variations where critical (e.g., "CRISPR" OR "Cas9")
      - Prioritize high-impact nouns over verbs/adjectives
      - Exclude stop words and Boolean operators

  optional_parameters:
  - name: max_papers
    type: INTEGER
    detailed_type: MAX_PAPER_NUM
    description: The maximum number of articles you want to get. Default is 3.
    default: 3
  - name: start_date
    type: DATE
    detailed_type: DATE
    description: The date from which you want to start searching for articles. Use
      format "yyyy-mm-dd", e.g., "2024-03-19". Default(empty input) is 3 years ago
      from today. The start date must be the same or earlier than the end date.
    default: ~
  - name: end_date
    type: DATE
    detailed_type: DATE
    description: The date up to which you want to search for articles. Use format
      "yyyy-mm-dd", e.g. "2024-03-19". Default(empty input) is today's date.
    default: ~
  return_values:
  - name: paper_title
    type: TEXT
    detailed_type: TEXT
    description: The title of the article.
  - name: paper_date
    type: DATE
    detailed_type: DATE
    description: The publication date of the article.
  - name: paper_link
    type: TEXT
    detailed_type: URL
    description: The link to the article.
  - name: paper_doi
    type: TEXT
    detailed_type: DOI
    description: The DOI (Digital Object Identifier) of the article.
  return_scores:
  - name: paper_count
    description: The paper_count represents the total number of articles retrieved
      from the biorxiv preprint server based on the specified search criteria.
  - name: duration
    description: Total time spent searching (unit of measurement in seconds).