conda_root: /root/anaconda3/condabin/conda

agent:
  model_py_path: llama3/model
  # path: /sujin/Models/Llama/arcee-ai/Llama-3.1-SuperNova-Lite
  path: modelhub/Llama-3.1-SuperNova-Lite
  max_new_tokens: 1024
  top_p: 0.8
  top_k: null
  temperature: 0.1
  repetition_penalty: 1.0
  stop_words: [<|eot_id|>]

use_GPT: False

data_dir: ~

caller_root: tool_caller
pipeline_only: False

data:
  input: examples/inputs/saprot/saprot_input.json
  output: outputs/saprot_output.json

toolset:
  func_hub_dir: funchub
  kwargs: ~

setting:
  seed: 20000812
  os_environ:
    WANDB_API_KEY: 3a9aeef6a84f90c1b00b61633fde8e3cdf207c28
    WANDB_RUN_ID: ~
    # WANDB_MODE: offline
    CUDA_VISIBLE_DEVICES: 0
    MASTER_PORT: 12315
    MASTER_ADDR: localhost
    WORLD_SIZE: 1
    NODE_RANK: 0
    RANK: 0
    OMP_NUM_THREADS: 1
  wandb_config:
    project: ProteinAgent
    name: uniprot_selector

selector:
#    Which model to use
  # model_py_path: tool_selector/retriever_selector
  kwargs: 
    model_path: Retriever/multi-qa-mpnet-base-dot-v1