conda_root: /home/public/miniconda3/condabin/conda

agent:
  model_py_path: llama3/model
  # path: /sujin/Models/Llama/arcee-ai/Llama-3.1-SuperNova-Lite
  path: /home/public/modelhub/arcee-ai/Llama-3.1-SuperNova-Lite
  max_new_tokens: 1024
  top_p: 0.8
  top_k: null
  temperature: 0.1
  repetition_penalty: 1.0
  stop_words: [<|eot_id|>]
  interpreter:
    path: /home/public/modelhub/Phi-3-mini-128k-instruct
    max_new_tokens: 500
    return_full_text: False
    temperature: 1.0
    do_sample: False

use_GPT: False

data_dir: 
  huggingface_root: /home/public/huggingface
  bin_root: /home/public/bin
  modelhub_root: /home/public/modelhub
  dataset_root: /home/public/dataset

caller_root: tool_caller
pipeline_only: False

data:
  input: examples/inputs/saprot/saprot_input.json
  output: outputs/saprot_output.json

toolset:
  func_hub_dir: /sujin/PycharmProjects/ProtAgent/funchub
  kwargs: ~

setting:
  seed: 20000812
  os_environ:
    WANDB_API_KEY: 3a9aeef6a84f90c1b00b61633fde8e3cdf207c28
    WANDB_RUN_ID: ~
    # WANDB_MODE: offline
    CUDA_VISIBLE_DEVICES: 1,2,3
    MASTER_PORT: 12315
    MASTER_ADDR: localhost
    WORLD_SIZE: 1
    NODE_RANK: 0
    RANK: 0
    OMP_NUM_THREADS: 1
  wandb_config:
    project: ProteinAgent
    name: uniprot_selector

selector:
#    Which model to use
#   model_py_path: tool_selector/retriever_selector
  kwargs: 
    model_path: Retriever/multi-qa-mpnet-base-dot-v1
