mode: single_cdr
model:
  checkpoint: huggingface/DiffAb/DiffAb/fixbb.pt

sampling:
  seed: 2022
  sample_structure: false
  sample_sequence: true
  cdrs:
    - H_CDR1
    - H_CDR2
    - H_CDR3
    - L_CDR1
    - L_CDR2
    - L_CDR3
  num_samples: 10
