mode: single_cdr
model:
  checkpoint: huggingface/DiffAb/DiffAb/structure_pred.pt

sampling:
  seed: 2022
  sample_structure: true
  sample_sequence: false
  cdrs:
    - H_CDR1
    - H_CDR2
    - H_CDR3
    - L_CDR1
    - L_CDR2
    - L_CDR3
  num_samples: 10
